### ISSUE TITLE
Remove google analytics :)

### ISSUE THREAD

**Issue by RizRiyz** [s0lst1c3/s0lst1c3.github.io#1]
Please help me remove this code from your website :) already mentioned you on twitter 

https://twitter.com/ariestiyansyah/status/1107392741351120896

https://github.com/s0lst1c3/s0lst1c3.github.io/blob/37923c0ff5ee4d9bd578752db56796ec63ebbc75/_includes/analytics.html#L7

Appreciate your help and thank you for using naringu theme.

**Comment by s0lst1c3** [comment]
Thanks for letting me know about this. Fixed.
